=== ye1ss/DAM/IFP DAM (primerAño)/LENGUAJE DE MARCAS/3 EVALUACIÓN/LDM_DAM_ACT3b_Del Rosario_Yeismil/Datos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Curriculum">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datosPersonales">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="name" />
                            <xs:element name="apellido" type="name" />
                            <xs:element name="sexo" type="sexo" />
                            <xs:element name="fechaNacimiento" type="fecha" />
                            <xs:element name="Nacionalidad" type="caracter" />
                            <xs:element name="DNI" type="dni" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datosContacto">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tipoVia" type="caracter" />
                            <xs:element name="nombre" type="caracter" />
                            <xs:element name="numero" type="caracter" />
                            <xs:element name="puerta" type="caracter" />
                            <xs:element name="codigoPostal" type="cp" />
                            <xs:element name="pais" type="caracter" />
                            <xs:element name="email" type="caracter" />
                            <xs:element name="telefono" type="telefono" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="formacion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tituloObtenido" type="caracter" />
                                        <xs:element name="fechaInicio" type="fecha" />
                                        <xs:element name="fechaFin" type="fecha" />
                                        <xs:element name="institucion" type="caracter" />
                                        <xs:element name="nombreTitulo" minOccurs="0"
                                            type="caracter" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="idiomas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lenguaMaterna" type="caracter" />
                            <xs:element name="idioma" type="caracter" />
                            <xs:element name="nivel" type="nivel" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="experienciaLaboral">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="trabajo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="lugar" type="caracter" />
                                        <xs:element name="cargo" type="caracter" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="competenciasInformaticas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="software">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="caracter" />
                                        <xs:element name="nivel" type="nivel" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datosAdicionales">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="aficciones" type="caracter" />
                            <xs:element name="vehiculoPropio" type="sino" />
                            <xs:element name="disponibilidadViajes" type="sino" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z\s]+"/>
            <xs:maxLength value="30"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dni">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{8}[a-zA-Z]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="fecha">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}/\d{2}/\d{4}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="caracter">
        <xs:restriction base="xs:string">
        <xs:maxLength value="50"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="sexo">
        <xs:restriction base="xs:string">
            <xs:pattern value="masculino|femenino"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cp">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="telefono">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{9}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="nivel">
        <xs:restriction base="xs:string">
            <xs:pattern value="bajo|medio|alto"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="sino">
        <xs:restriction base="xs:string">
            <xs:pattern value="si|no"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ye1ss/DAM/IFP DAM (primerAño)/LENGUAJE DE MARCAS/LENGUAJE DE MARCAS/3 EVALUACIÓN/LDM_DAM_ACT3b_Del Rosario_Yeismil/Datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<Curriculum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Datos.xsd">
    <datosPersonales>
        <nombre>Yeismil</nombre>
        <apellido>Del Rosario</apellido>
        <sexo>masculino</sexo>
        <fechaNacimiento>29/04/2002</fechaNacimiento>
        <Nacionalidad>Dominicana y Española</Nacionalidad>
        <DNI>54495517F</DNI>
    </datosPersonales>
    <datosContacto>
        <tipoVia>Calle</tipoVia>
        <nombre>Isla de Corcega</nombre>
        <numero>20</numero>
        <puerta>20</puerta>
        <codigoPostal>28100</codigoPostal>
        <pais>España</pais>
        <email>yeismil18@gmail.com</email>
        <telefono>672442215</telefono>
    </datosContacto>
    <formacion>
        <titulo>
            <tituloObtenido>ESO</tituloObtenido>
            <fechaInicio>20/10/2015</fechaInicio>
            <fechaFin>13/05/2020</fechaFin>
            <institucion>Miguel Delibes</institucion>
        </titulo>
        <titulo>
            <tituloObtenido>Actividades Comerciales</tituloObtenido>
            <fechaInicio>20/10/2020</fechaInicio>
            <fechaFin>14/05/2022</fechaFin>
            <institucion>IES Vigen de la Paz</institucion>
            <nombreTitulo>Grado Medio</nombreTitulo>
        </titulo>
    </formacion>
    <idiomas>
        <lenguaMaterna>Español</lenguaMaterna>
        <idioma>Ingles</idioma>
        <nivel>medio</nivel>
    </idiomas>
    <experienciaLaboral>
        <trabajo>
            <lugar>Dominos Pizza</lugar>
            <cargo>Sala</cargo>   
        </trabajo>
        <trabajo>
            <lugar>Telepizza</lugar>
            <cargo>Repartidor</cargo>   
        </trabajo>
        <trabajo>
            <lugar>Goiko Grill</lugar>
            <cargo>Aydante de Cocinero</cargo>   
        </trabajo>
        <trabajo>
            <lugar>Dominos Pizza</lugar>
            <cargo>Repartidor</cargo>   
        </trabajo>
    </experienciaLaboral>
    <competenciasInformaticas>
        <software>
            <nombre>Windows</nombre>
            <nivel>medio</nivel>
        </software>
    </competenciasInformaticas>
    <datosAdicionales>
        <aficciones>Juegos de Ordenador</aficciones>
        <vehiculoPropio>si</vehiculoPropio>
        <disponibilidadViajes>si</disponibilidadViajes>
    </datosAdicionales>

</Curriculum>
