=== ye1ss/DAM/IFP DAM (primerAño)/LENGUAJE DE MARCAS/3 EVALUACIÓN/LDM_DAM_ACT3b_Del Rosario_Yeismil/rugby.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="temporada">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="jornada" minOccurs="5" maxOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="partido" maxOccurs="3">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="fecha" type="xs:date" />
                                        <xs:element name="estadio">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="espectadores"
                                                            type="tipoEspectador" default="0"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="local" type="tipoEquipo" />
                                        <xs:element name="visitante" type="tipoEquipo" />
                                        <xs:choice>
                                            <xs:element name="resultado" minOccurs="0" maxOccurs="1">
                                                <xs:complexType>
                                                    <xs:attribute name="local" type="xs:integer"
                                                        use="required" />
                                                    <xs:attribute name="visitante" type="xs:integer"
                                                        use="required" />
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="aplazado" minOccurs="0" maxOccurs="1"/>
                                        </xs:choice>
                                    </xs:sequence>
                                    <xs:attribute name="numero" type="xs:integer" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="numero" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="aÃ±o" type="xs:integer" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:annotation>
        <xs:documentation>
            Restriccion espectadores
        </xs:documentation>
    </xs:annotation>
    <xs:simpleType name="tipoEspectador">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="80000"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>
    <xs:annotation>
        <xs:documentation>
            equipos disponibles
        </xs:documentation>
    </xs:annotation>
    <xs:simpleType name="tipoEquipo">
        <xs:restriction base="xs:string">
            <xs:pattern value="Gales|Inglaterra|Irlanda|Francia|Escocia|Italia"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoJornada">
        <xs:restriction base="xs:integer">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="5"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ye1ss/DAM/IFP DAM (primerAño)/LENGUAJE DE MARCAS/3 EVALUACIÓN/LDM_DAM_ACT3b_Del Rosario_Yeismil/rugby.xml
<?xml version="1.0" encoding="UTF-8"?>
<temporada xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="rugby.xsd" aÃ±o="2002">
    <jornada numero="1">
        <partido numero="1">
            <fecha>2000-02-02</fecha>
            <estadio espectadores="46900">Landsdowne Road</estadio>
            <local>Irlanda</local>
            <visitante>Inglaterra</visitante>
            <resultado local="23" visitante="8"/>
        </partido>
        <partido numero="2">
            <fecha>2000-02-03</fecha>
            <estadio>El parque de los principes</estadio>
            <local>Francia</local>
            <visitante>Gales</visitante>
            <aplazado/>
        </partido>
        <partido numero="3">
            <fecha>2000-02-03</fecha>
            <estadio>Estadio Olimpico de Roma</estadio>
            <local>Italia</local>
            <visitante>Escocia</visitante>
            <resultado local="2" visitante="20"/>
        </partido>
    </jornada>
    <jornada numero="2">
        <partido numero="1">
            <fecha>2000-02-10</fecha>
            <estadio espectadores="56000">Parque de los principes</estadio>
            <local>Francia</local>
            <visitante>Inglaterra</visitante>
            <resultado local="15" visitante="20"/>
        </partido>
        <partido numero="2">
            <fecha>2000-02-10</fecha>
            <estadio>Landsdowne Road</estadio>
            <local>Irlanda</local>
            <visitante>Escocia</visitante>
            <aplazado/>
        </partido>
        <partido numero="3">
            <fecha>2000-02-11</fecha>
            <estadio espectadores="0">Millennium Stadium</estadio>
            <local>Gales</local>
            <visitante>Italia</visitante>
            <aplazado/>
        </partido>
    </jornada>
    <jornada numero="3">
        <partido numero="1">
            <fecha>2000-02-02</fecha>
            <estadio espectadores="80000">Murrayfield</estadio>
            <local>Escocia</local>
            <visitante>Inglaterra</visitante>
            <resultado local="23" visitante="6"/>
        </partido>
        <partido numero="2">
            <fecha>2000-02-03</fecha>
            <estadio espectadores="45000">El parque de los principes</estadio>
            <local>Francia</local>
            <visitante>Italia</visitante>
            <resultado local="3" visitante="34"/>
        </partido>
        <partido numero="3">
            <fecha>2000-02-03</fecha>
            <estadio>Landsdowne Road</estadio>
            <local>Irlanda</local>
            <visitante>Gales</visitante>
            <aplazado/>
            
        </partido>
    </jornada>
    <jornada numero="4">
        <partido numero="1">
            <fecha>2000-02-02</fecha>
            <estadio espectadores="46900">Landsdowne Road</estadio>
            <local>Italia</local>
            <visitante>Inglaterra</visitante>
            <resultado local="12" visitante="18"/>
        </partido>
        <partido numero="2">
            <fecha>2000-02-03</fecha>
            <estadio>El parque de los principes</estadio>
            <local>Francia</local>
            <visitante>Gales</visitante>
            <aplazado/>
        </partido>
        <partido numero="3">
            <fecha>2000-02-03</fecha>
            <estadio>El parque de los principes</estadio>
            <local>Francia</local>
            <visitante>Gales</visitante>
            <aplazado/>
        </partido>
    </jornada>
    <jornada numero="5">
        <partido numero="1">
            <fecha>2000-02-02</fecha>
            <estadio espectadores="46900">Landsdowne Road</estadio>
            <local>Irlanda</local>
            <visitante>Inglaterra</visitante>
            <resultado local="11" visitante="2"/>
        </partido>
        <partido numero="2">
            <fecha>2000-02-03</fecha>
            <estadio>El parque de los principes</estadio>
            <local>Francia</local>
            <visitante>Gales</visitante>
            <aplazado/>
        </partido>
        <partido numero="3">
            <fecha>2000-02-03</fecha>
            <estadio>El parque de los principes</estadio>
            <local>Francia</local>
            <visitante>Gales</visitante>
            <aplazado/>
        </partido>
    </jornada>
</temporada>
